name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: '1.0.0'
        required: true

jobs:
  publish:
    name: Publish library at mavenCentral
    runs-on: macOS-latest
    env:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEYID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_KEY: ${{ secrets.GPG_KEY_CONTENTS }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prebuild library
        run: ./gradlew publishToMavenLocal
      - name: Publish library
        run: ./gradlew publish --no-parallel
  release:
    name: Create release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          commitish: ${{ github.ref }}
          tag_name: release/${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: "Empty body filled here"
          draft: true