name: Publish release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: SebRollen/toml-action@v1.0.2
        id: version
        with:
          file: 'gradle/libs.versions.toml'
          field: 'versions.library-version-string'
      - uses: SebRollen/toml-action@v1.0.2
        id: name
        with:
          file: 'gradle/libs.versions.toml'
          field: 'versions.library-name'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.value }}
          release_name: ${{ steps.name.outputs.value }} - ${{ steps.version.outputs.value }}
          body: "Empty body filled here"
          draft: false
          prerelease: true